name: Create Release

on:
  workflow_dispatch:
    branches: [develop]
    inputs:
      version:
        description: Version to release
        required: true
        type: string
      confirm-version:
        description: Confirm version
        required: true
        type: string

jobs:
  verify-version:
    name: Verify release version
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
      CONFIRM_VERSION: ${{ github.event.inputs.confirm-version }}
    steps:
      - run: if [[ $VERSION != $CONFIRM_VERSION ]]; then echo "Version mismatch"; exit 1; fi

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: verify-version
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: vendor/bin/phpunit

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Config git
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"

      - name: Rebase master from develop
        run: |
          git fetch --no-tags
          git tag ${{ github.event.inputs.version }}
          git rebase origin/develop
          git push
          git push --tags
