name: PHPUnit

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: composer install
    
    - name: Run tests
      run: vendor/bin/phpunit